#!/usr/bin/env node
/*
 * publish.js — build every app and (re)generate the site landing page in /docs
 *
 * Usage:  node scripts/publish.js     (or: npm run publish)
 *
 * Reads apps.json (the app registry). For each app it:
 *   1. runs the app's build step (e.g. Markdown -> JSON), if it has one
 *   2. confirms the app folder exists under /docs
 * Then it regenerates docs/index.html — the landing page that lists every app.
 *
 * To publish a NEW app: drop its folder in /docs and add an entry to apps.json.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');
const REGISTRY = path.join(ROOT, 'apps.json');

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function landingHTML(site, apps) {
  const cards = apps.map((a) => `      <a class="app-card" href="./${esc(a.slug)}/">
        <span class="ic"><img src="./${esc(a.icon || a.slug + '/icons/icon-192.png')}" alt="" /></span>
        <span>
          <p class="t">${esc(a.title)}</p>
          <p class="d">${esc(a.description || '')}</p>
        </span>
        <span class="chev">›</span>
      </a>`).join('\n');

  const firstIcon = esc((apps[0] && (apps[0].icon || apps[0].slug + '/icons/icon-192.png')) || '');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <meta name="theme-color" content="#2f5d50" />
  <title>${esc(site.title)}</title>
  <link rel="icon" href="./${firstIcon}" />
  <link rel="apple-touch-icon" href="./${firstIcon}" />
  <style>
    :root{ color-scheme: light;
      --green:#2f5d50; --green-dark:#234a3f; --sand:#f4efe6; --ink:#22312c;
      --muted:#6b7770; --line:#e4e0d6; --accent:#d98324;
      --radius:16px; --shadow:0 2px 10px rgba(0,0,0,.06); }
    *{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
    html,body{margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
      background:var(--sand);color:var(--ink);line-height:1.5;min-height:100vh}
    header{background:var(--green);color:#fff;padding:calc(28px + env(safe-area-inset-top)) 20px 26px;
      box-shadow:0 2px 8px rgba(0,0,0,.15)}
    .head-inner{max-width:820px;margin:0 auto;display:flex;align-items:center;gap:16px}
    .logo{width:58px;height:58px;border-radius:16px;flex:0 0 auto}
    header h1{margin:0;font-size:1.5rem}
    header p{margin:4px 0 0;opacity:.88;font-size:.95rem}
    main{max-width:820px;margin:0 auto;padding:20px 16px 40px}
    .section-label{font-size:.78rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);
      font-weight:700;margin:6px 4px 10px}
    .apps{display:grid;grid-template-columns:1fr;gap:12px}
    @media(min-width:620px){.apps{grid-template-columns:1fr 1fr}}
    a.app-card{display:flex;align-items:center;gap:14px;text-decoration:none;color:inherit;
      background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:16px;
      box-shadow:var(--shadow);transition:transform .08s ease}
    a.app-card:active{transform:scale(.985)}
    .app-card .ic{width:52px;height:52px;border-radius:13px;overflow:hidden;flex:0 0 auto;background:#eef5f1}
    .app-card .ic img{width:100%;height:100%;object-fit:cover;display:block}
    .app-card .t{font-weight:700;font-size:1.08rem;margin:0 0 2px}
    .app-card .d{font-size:.9rem;color:var(--muted);margin:0}
    .app-card .chev{margin-left:auto;color:var(--muted);font-size:1.4rem}
    footer{max-width:820px;margin:0 auto;padding:0 16px 40px;color:var(--muted);font-size:.82rem;text-align:center}
  </style>
</head>
<body>
  <header>
    <div class="head-inner">
      <img class="logo" src="./${firstIcon}" alt="" />
      <div>
        <h1>${esc(site.title)}</h1>
        <p>${esc(site.subtitle || '')}</p>
      </div>
    </div>
  </header>
  <main>
    <div class="section-label">Apps</div>
    <div class="apps">
${cards}
    </div>
  </main>
  <footer>Generated by scripts/publish.js — edit apps.json to add an app.</footer>
</body>
</html>
`;
}

// Stamp a fresh cache version into an app's service worker so deploys invalidate
// the old cached app shell (otherwise returning visitors keep seeing the old version).
function bumpServiceWorker(appDir, buildId) {
  const swPath = path.join(appDir, 'sw.js');
  if (!fs.existsSync(swPath)) return false;
  let sw = fs.readFileSync(swPath, 'utf8');
  const re = /(const VERSION = ')[^']*(';)/;
  if (!re.test(sw)) return false;
  sw = sw.replace(re, `$1rvguide-${buildId}$2`);
  fs.writeFileSync(swPath, sw);
  return true;
}

function main() {
  if (!fs.existsSync(REGISTRY)) { console.error('Missing apps.json'); process.exit(1); }
  const reg = JSON.parse(fs.readFileSync(REGISTRY, 'utf8'));
  const apps = reg.apps || [];
  const buildId = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12); // YYYYMMDDHHMM
  console.log(`Publishing ${apps.length} app(s) to /docs  (build ${buildId})\n`);

  apps.forEach((a) => {
    const appDir = path.join(DOCS, a.slug);
    if (!fs.existsSync(appDir)) {
      console.warn(`  ! ${a.slug}: folder docs/${a.slug} not found — skipping build`);
      return;
    }
    if (a.build) {
      const buildPath = path.join(appDir, a.build);
      if (fs.existsSync(buildPath)) {
        process.stdout.write(`  • ${a.slug}: building… `);
        execFileSync('node', [buildPath], { stdio: ['ignore', 'ignore', 'inherit'] });
        process.stdout.write('done');
      } else {
        console.warn(`  ! ${a.slug}: build script ${a.build} not found — skipping`);
      }
    } else {
      process.stdout.write(`  • ${a.slug}: static (no build step)`);
    }
    if (bumpServiceWorker(appDir, buildId)) process.stdout.write('  [sw cache bumped]');
    console.log('');
  });

  const html = landingHTML(reg.site || { title: 'Apps' }, apps);
  fs.writeFileSync(path.join(DOCS, 'index.html'), html);
  console.log(`\nWrote docs/index.html (landing page, ${apps.length} app card(s)).`);
  console.log('Publish complete. Commit and push, and GitHub Pages will serve /docs.');
}

main();
